//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Integration.MLP.Tests.IntegrationAcceptanceTestDefinitions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivitySubmissionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivitySubmissionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Integration.MLP.Tests.IntegrationAcceptanceTestDefinitions.ActivitySubmis" +
                            "sionResource", typeof(ActivitySubmissionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Essay Qestion Activity.
        /// </summary>
        internal static string ActivitySubmision_EssayQuestion_Answer_Text_Value {
            get {
                return ResourceManager.GetString("ActivitySubmision_EssayQuestion_Answer_Text_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mundo hispano 01-01. Before Viewing. Where is Spanish spoken?.
        /// </summary>
        internal static string ActivitySubmision_ManuallyGradable_Activity_Name {
            get {
                return ResourceManager.GetString("ActivitySubmision_ManuallyGradable_Activity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.1.
        /// </summary>
        internal static string ActivitySubmision_SubmittedActivity_GradeValue {
            get {
                return ResourceManager.GetString("ActivitySubmision_SubmittedActivity_GradeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string ActivitySubmission_ManuallySubmitted_Activity_GradeValue {
            get {
                return ResourceManager.GetString("ActivitySubmission_ManuallySubmitted_Activity_GradeValue", resourceCulture);
            }
        }
    }
}
