//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.DRT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DRTDefaultUXPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DRTDefaultUXPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.DRT.DRTDefaultUXPageResource", typeof(DRTDefaultUXPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_imgBtnAdd_Close.
        /// </summary>
        internal static string DRTDefaultUX_Page_AddandClose_Button_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_AddandClose_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;contentarea&apos;]/tbody/tr/td[1]/div/table[2]/thead/tr[3]/td/span.
        /// </summary>
        internal static string DRTDefaultUX_Page_AddExistingActivity_Link_Xpath_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_AddExistingActivity_Link_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0:_ctl0:phBody:PageContent:FrmDRTTestsPanel1:btnimg.
        /// </summary>
        internal static string DRTDefaultUX_Page_BeginButton_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_BeginButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0__ctl0_phBody_PageContent_lbtnSave.
        /// </summary>
        internal static string DRTDefaultUX_Page_content_SaveButton_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_content_SaveButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string DRTDefaultUX_Page_Content_WindowName {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Content_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skill Study Plan.
        /// </summary>
        internal static string DRTDefaultUX_Page_CreateSkillStudyPlan_Window_Name {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_CreateSkillStudyPlan_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180000.
        /// </summary>
        internal static string DRTDefaultUX_Page_CustomTimeForCreateSSPWindow_Value {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_CustomTimeForCreateSSPWindow_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill Study Plan.
        /// </summary>
        internal static string DRTDefaultUX_Page_Edit_WindowName {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Edit_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0:_ctl0:phBody:PageContent:FrmDRTTestsPanel1:btnimg.
        /// </summary>
        internal static string DRTDefaultUX_Page_PageContent_BeginButton_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PageContent_BeginButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0:_ctl0:phBody:PageContent:lbtnBack.
        /// </summary>
        internal static string DRTDefaultUX_Page_PageContent_ReturnToCourseButton_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PageContent_ReturnToCourseButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0__ctl0_phBody_PageContent_FrmDRTTestsPanel1_DTScore.
        /// </summary>
        internal static string DRTDefaultUX_Page_PageContent_Score_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PageContent_Score_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0:_ctl0:phBody:PageContent:FrmDRTTestsPanel1:postimg.
        /// </summary>
        internal static string DRTDefaultUX_Page_PostTest_BeginButton_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PostTest_BeginButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;sp_DRTTestPanel_Div&apos;]/table[5]/thead/tr[2]/td/img.
        /// </summary>
        internal static string DRTDefaultUX_Page_Posttest_Img_Xpath_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Posttest_Img_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Post-test.
        /// </summary>
        internal static string DRTDefaultUX_Page_PostTest_Window_Name {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PostTest_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;sp_DRTTestPanel_Div&apos;]/table[2]/thead/tr[2]/td/img.
        /// </summary>
        internal static string DRTDefaultUX_Page_Pretest_Img_Xpath_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Pretest_Img_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messageBoardTextblk.
        /// </summary>
        internal static string DRTDefaultUX_Page_PreTestCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_PreTestCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;_ctl0:_ctl0:phBody:PageContent:lbtnBack&apos;].
        /// </summary>
        internal static string DRTDefaultUX_Page_ReturnToCourse_Xpath_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_ReturnToCourse_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0__ctl0_phBody_PageContent_lbtnSave.
        /// </summary>
        internal static string DRTDefaultUX_Page_SaveandReturn_Button_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_SaveandReturn_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Return.
        /// </summary>
        internal static string DRTDefaultUX_Page_SaveandReturn_Link_PartialLinktext_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_SaveandReturn_Link_PartialLinktext_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;_ctl0__ctl0_phBody_PageContent_lbtnSave&apos;].
        /// </summary>
        internal static string DRTDefaultUX_Page_SaveandReturn_Xpath_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_SaveandReturn_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 10 Test.
        /// </summary>
        internal static string DRTDefaultUX_Page_Search_PretestActivity {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Search_PretestActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Questions.
        /// </summary>
        internal static string DRTDefaultUX_Page_SelectQuestions_Window_Name {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_SelectQuestions_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Study Plan.
        /// </summary>
        internal static string DRTDefaultUX_Page_StudyPlan_Window_Name {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_StudyPlan_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Study Plan.
        /// </summary>
        internal static string DRTDefaultUX_Page_Studyplan_WindowName {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_Studyplan_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0__ctl0_phBody_PageContent_txtModuleName.
        /// </summary>
        internal static string DRTDefaultUX_Page_StudyplanName_Input_Id_Locator {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_StudyplanName_Input_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkillStudyplan.
        /// </summary>
        internal static string DRTDefaultUX_Page_StudyplanName_Value {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_StudyplanName_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string DRTDefaultUX_Page_WaitElement_Thread_Time {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_WaitElement_Thread_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DRTDefaultUX_Page_WaitForElement_Time_Value {
            get {
                return ResourceManager.GetString("DRTDefaultUX_Page_WaitForElement_Time_Value", resourceCulture);
            }
        }
    }
}
