//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Acceptance.MyItLab.GraderIT.Tests.CommonProductAcceptanceTestDefinitions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStepsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStepsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Acceptance.MyItLab.GraderIT.Tests.CommonProductAcceptanceTestDefinitions." +
                            "CommonStepsResource", typeof(CommonStepsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is Processing and will be available soon.
        /// </summary>
        internal static string CommonSteps_AssignToCopyState_Text_Value {
            get {
                return ResourceManager.GetString("CommonSteps_AssignToCopyState_Text_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Courses.
        /// </summary>
        internal static string CommonSteps_CreateNewCoursesWindow_Name_Locator {
            get {
                return ResourceManager.GetString("CommonSteps_CreateNewCoursesWindow_Name_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        internal static string CommonSteps_CreateNewUserWindow_Name_Locator {
            get {
                return ResourceManager.GetString("CommonSteps_CreateNewUserWindow_Name_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrm.
        /// </summary>
        internal static string CommonSteps_IFrame {
            get {
                return ResourceManager.GetString("CommonSteps_IFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string CommonSteps_LeftFrame {
            get {
                return ResourceManager.GetString("CommonSteps_LeftFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not opened in the specified amount of time..
        /// </summary>
        internal static string CommonSteps_PageNotOpened_Message {
            get {
                return ResourceManager.GetString("CommonSteps_PageNotOpened_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string CommonSteps_RightFrame {
            get {
                return ResourceManager.GetString("CommonSteps_RightFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string CommonSteps_SleepTime_Value {
            get {
                return ResourceManager.GetString("CommonSteps_SleepTime_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messageBoardText.
        /// </summary>
        internal static string CommonSteps_SuccessMessage_Class_Locator {
            get {
                return ResourceManager.GetString("CommonSteps_SuccessMessage_Class_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PegasusMessageBoard.
        /// </summary>
        internal static string CommonSteps_SuccessMessage_Id_Locator {
            get {
                return ResourceManager.GetString("CommonSteps_SuccessMessage_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string CommonSteps_WaitTimeOut_Value {
            get {
                return ResourceManager.GetString("CommonSteps_WaitTimeOut_Value", resourceCulture);
            }
        }
    }
}
