//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RptActivityResultByStudentPageRecource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RptActivityResultByStudentPageRecource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.Reports.RptActivityResultByStudentPageReco" +
                            "urce", typeof(RptActivityResultByStudentPageRecource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;_ctl3_AveragePlaceHolder&apos;]/table/tbody/tr/td[1]/span.
        /// </summary>
        internal static string RptActivityResultByStudentPage_ActivityAverage_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_ActivityAverage_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;_ctl3_allAssementDetail1&apos;]/table/tbody/tr[{0}]/td/div/table/tbody/tr/td/span.
        /// </summary>
        internal static string RptActivityResultByStudentPage_ActivityDetails_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_ActivityDetails_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;lblContainer&apos;]/div/div/table[2]/tbody/tr/td/div/table/tbody/tr.
        /// </summary>
        internal static string RptActivityResultByStudentPage_ActivityStudentCount_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_ActivityStudentCount_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;lblContainer&apos;]/div/div/table[2]/tbody/tr/td/div/table/tbody/tr[{0}]/td[1]/span.
        /// </summary>
        internal static string RptActivityResultByStudentPage_ActivityStudentName_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_ActivityStudentName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/span[2]/div/div/table[2]/tbody/tr/td/div/table/tbody/tr[{0}]/td[2]/table/tbody/tr[2]/td/table[1]/tbody/tr/td[4].
        /// </summary>
        internal static string RptActivityResultByStudentPage_ActivityStudentScore_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_ActivityStudentScore_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/span[2]/div/div/table[2]/tbody/tr/td/div/table/tbody/tr[{0}]/td[3]/table/tbody/tr[2]/td/table[1]/tbody/tr/td[4].
        /// </summary>
        internal static string RptActivityResultByStudentPage_AdminActivityStudentScore_XPath_Locator {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_AdminActivityStudentScore_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report: Activity Results by Student.
        /// </summary>
        internal static string RptActivityResultByStudentPage_WindowName {
            get {
                return ResourceManager.GetString("RptActivityResultByStudentPage_WindowName", resourceCulture);
            }
        }
    }
}
