//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.TeacherSharedLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentLibraryPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentLibraryPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.TeacherSharedLibrary.ContentLibraryPageRes" +
                            "ource", typeof(ContentLibraryPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table[{0}]/tbody/tr/td[2]/div/table/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/span.
        /// </summary>
        internal static string ContentLibrary_Page_AssetCopyMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_AssetCopyMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table[{0}]/tbody/tr/td[2]/div/table/tbody/tr/td[2]/table[1].
        /// </summary>
        internal static string ContentLibrary_Page_AssetName_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_AssetName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table.
        /// </summary>
        internal static string ContentLibrary_Page_Assets_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_Assets_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is being prepared and will be available soon..
        /// </summary>
        internal static string ContentLibrary_Page_AssignToCopy_Message {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_AssignToCopy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table.
        /// </summary>
        internal static string ContentLibrary_Page_Folder_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_Folder_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ContentLibrary_Page_ForLoopInitialization_Value {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_ForLoopInitialization_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmCurriculum.
        /// </summary>
        internal static string ContentLibrary_Page_Frame_Id_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_Frame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn21Nodes&apos;]/table[{0}]/tbody/tr/td[4]//tr/td[2]/table/tbody/tr/td[2]//img.
        /// </summary>
        internal static string ContentLibrary_Page_Lessson_CmenuIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_Lessson_CmenuIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn2Nodes&apos;]/table.
        /// </summary>
        internal static string ContentLibrary_Page_SubFolder_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_SubFolder_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn2Nodes&apos;]/table[{0}]/tbody/tr/td[3]//td[2]//td[1].
        /// </summary>
        internal static string ContentLibrary_Page_SubFolder_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentLibrary_Page_SubFolder_Name_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is being prepared and will be available soon..
        /// </summary>
        internal static string ContnetLibrary_Page_Activity_AssignToCopy_Message {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Activity_AssignToCopy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;VTOC_col1&apos;]/table/tbody/tr/td[4]/img.
        /// </summary>
        internal static string ContnetLibrary_Page_Activity_CmenuIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Activity_CmenuIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Content.
        /// </summary>
        internal static string ContnetLibrary_Page_ActivityCMenuOptionName {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_ActivityCMenuOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdAssetIcon.
        /// </summary>
        internal static string ContnetLibrary_Page_ActivityIcon_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_ActivityIcon_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucContentManager_tvContentt0.
        /// </summary>
        internal static string ContnetLibrary_Page_ActivityName_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_ActivityName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lnkAdvSearchTslCC.
        /// </summary>
        internal static string ContnetLibrary_Page_AdvancedSearchLink_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_AdvancedSearchLink_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;diMenuOptions&apos;]/table/tbody/tr/td/div[2].
        /// </summary>
        internal static string ContnetLibrary_Page_Asset_Cmenu_Options_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Asset_Cmenu_Options_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignedToCopyInterval.
        /// </summary>
        internal static string ContnetLibrary_Page_AssignToCopyInterval {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_AssignToCopyInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucContentManager_ucMessageBoard_lnkClear.
        /// </summary>
        internal static string ContnetLibrary_Page_ClearResultLink_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_ClearResultLink_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucCurriculumSubNavigation_ucSearchViewOptions_rptViewByOptions__ctl2_LinkButtonVB.
        /// </summary>
        internal static string ContnetLibrary_Page_ContentTypeLink_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_ContentTypeLink_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;dvCurriculums&apos;]/ul/li[2].
        /// </summary>
        internal static string ContnetLibrary_Page_CustomContentLink_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_CustomContentLink_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ContnetLibrary_Page_CustomTimeToWait_Value {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_CustomTimeToWait_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucContentManager_tvContent.
        /// </summary>
        internal static string ContnetLibrary_Page_Div_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Div_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table[{0}]/tbody/tr/td[1]//img.
        /// </summary>
        internal static string ContnetLibrary_Page_FolderExpandButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_FolderExpandButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContent&apos;]/table[{0}]/tbody/tr/td[2].
        /// </summary>
        internal static string ContnetLibrary_Page_FolderName_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_FolderName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000.
        /// </summary>
        internal static string ContnetLibrary_Page_FrameRefresh_CustomTimeToWait_Value {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_FrameRefresh_CustomTimeToWait_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;divmainCmenu&apos;]/table/tbody/tr/td/div[2]/a.
        /// </summary>
        internal static string ContnetLibrary_Page_Lesson_CmenuCount_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Lesson_CmenuCount_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn21Nodes&apos;]/table[{0}]/tbody/tr/td[4]//td[3]//span/img.
        /// </summary>
        internal static string ContnetLibrary_Page_Lesson_CmenuIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Lesson_CmenuIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;divmainCmenu&apos;]/table/tbody/tr/td/div[2]/a[{0}].
        /// </summary>
        internal static string ContnetLibrary_Page_Lesson_CmenuOption_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Lesson_CmenuOption_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucContentManager_tvContentt27.
        /// </summary>
        internal static string ContnetLibrary_Page_LessonName_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_LessonName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn21Nodes&apos;]/table[{0}]/tbody/tr/td[4]//td[2]//td[1].
        /// </summary>
        internal static string ContnetLibrary_Page_LessonName_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_LessonName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucCurriculumSubNavigation_ProductNavigation_imgDrdProducts.
        /// </summary>
        internal static string ContnetLibrary_Page_Product_CmenuIcon_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Product_CmenuIcon_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;cr_product_dd_title&apos;].
        /// </summary>
        internal static string ContnetLibrary_Page_Productname_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Productname_Name_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputSearchBtn.
        /// </summary>
        internal static string ContnetLibrary_Page_SearchButton_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SearchButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dvAssetName.
        /// </summary>
        internal static string ContnetLibrary_Page_SearchedAssetName_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SearchedAssetName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputSearchBox.
        /// </summary>
        internal static string ContnetLibrary_Page_SearchTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SearchTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucCurriculumSubNavigation_ucSearchViewOptions_rptViewByOptions__ctl1_LinkButtonVB.
        /// </summary>
        internal static string ContnetLibrary_Page_SkillLink_Id_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SkillLink_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn21Nodes&apos;]/table.
        /// </summary>
        internal static string ContnetLibrary_Page_SubFolderContents_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SubFolderContents_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ucContentManager_tvContentn2Nodes&apos;]/table[{0}]/tbody/tr/td[2]//a/img.
        /// </summary>
        internal static string ContnetLibrary_Page_SubFolderExpandButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SubFolderExpandButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;PegasusMessageBoard&apos;]/span[2].
        /// </summary>
        internal static string ContnetLibrary_Page_SuccessMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_SuccessMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        internal static string ContnetLibrary_Page_Window_TitleName {
            get {
                return ResourceManager.GetString("ContnetLibrary_Page_Window_TitleName", resourceCulture);
            }
        }
    }
}
