ALTER TABLE [dbo].[BDD_Course]
    ADD CONSTRAINT [PK__BDD_Cour__C92D71870EA330E9] PRIMARY KEY CLUSTERED ([CourseID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

