ALTER TABLE [dbo].[BDD_ClassTypeLookUp]
    ADD CONSTRAINT [PK_BDD_ClassTypeLookUp] PRIMARY KEY CLUSTERED ([ClassTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

