ALTER TABLE [dbo].[BDD_ActivityTypeLookUp]
    ADD CONSTRAINT [PK_BDD_ActivityTypeLookUp] PRIMARY KEY CLUSTERED ([ActivityTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

