ALTER TABLE [dbo].[BDD_Program]
    ADD CONSTRAINT [PK_BDD_Program] PRIMARY KEY CLUSTERED ([ProgramID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

