//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Integration.eCollege {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitViewPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitViewPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Integration.eCollege.UnitViewPageResource", typeof(UnitViewPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA-01 Span Practice- Vocabulary: Saludos, despedidas y presentaciones.1.
        /// </summary>
        internal static string UnitViewPage_Activity_Name {
            get {
                return ResourceManager.GetString("UnitViewPage_Activity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;mainTable&apos;]/tbody/tr[2]/td/table/tbody/tr/th[{0}].
        /// </summary>
        internal static string UnitViewPage_ActivityName_Column_Xpath_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_ActivityName_Column_Xpath_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;mainTable&apos;]/tbody/tr[2]/td/table/tbody/tr[2]/td[{0}].
        /// </summary>
        internal static string UnitViewPage_ActivityName_Grade_Xpath_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_ActivityName_Grade_Xpath_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;mainTable&apos;]/tbody/tr[2]/td/table/tbody/tr.
        /// </summary>
        internal static string UnitViewPage_ActivityName_Row_Xpath_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_ActivityName_Row_Xpath_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;mainTable&apos;]/tbody/tr[2]/td/table/tbody/tr/th.
        /// </summary>
        internal static string UnitViewPage_ActivityName_TotalColumn_Xpath_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_ActivityName_TotalColumn_Xpath_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string UnitViewPage_Content_Frame_ID_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_Content_Frame_ID_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string UnitViewPage_Custom_Sleep_Time {
            get {
                return ResourceManager.GetString("UnitViewPage_Custom_Sleep_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goButton1.
        /// </summary>
        internal static string UnitViewPage_Go_Button_ID_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_Go_Button_ID_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gradebookViewDropDownList1.
        /// </summary>
        internal static string UnitViewPage_gradebookViewDropDown_ID_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_gradebookViewDropDown_ID_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string UnitViewPage_Main_Frame_ID_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_Main_Frame_ID_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -\r\n.
        /// </summary>
        internal static string UnitViewPage_Replace_Xtra__Character {
            get {
                return ResourceManager.GetString("UnitViewPage_Replace_Xtra__Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string UnitViewPage_Top_Frame_ID_locator {
            get {
                return ResourceManager.GetString("UnitViewPage_Top_Frame_ID_locator", resourceCulture);
            }
        }
    }
}
