//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Integration.SMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CourseIdInputPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourseIdInputPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Integration.SMS.CourseIdInputPageResource", typeof(CourseIdInputPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re done!.
        /// </summary>
        internal static string CourseIdInput_Page_Confirmation_Message_Value {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Confirmation_Message_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;wrapper-small&apos;]/h2.
        /// </summary>
        internal static string CourseIdInput_Page_Confirmation_Message_Xpath_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Confirmation_Message_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course-id-button.
        /// </summary>
        internal static string CourseIdInput_Page_CourseId_Continue_Button_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_CourseId_Continue_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course-id.
        /// </summary>
        internal static string CourseIdInput_Page_CourseId_Text_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_CourseId_Text_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string CourseIdInput_Page_Custom_TimeToWait_Element {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Custom_TimeToWait_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        internal static string CourseIdInput_Page_FindCourse_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_FindCourse_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access1.
        /// </summary>
        internal static string CourseIdInput_Page_Input_AccessCode_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Input_AccessCode_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verifyCourseID.
        /// </summary>
        internal static string CourseIdInput_Page_InputCourse_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_InputCourse_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string CourseIdInput_Page_NextButton_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_NextButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Selection.
        /// </summary>
        internal static string CourseIdInput_Page_ProductSelection_Window_Name {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_ProductSelection_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSMMNDStudentAccessCode.
        /// </summary>
        internal static string CourseIdInput_Page_SMS_AccessCode_MMNDStudent {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_SMS_AccessCode_MMNDStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessCodeToggleSingle.
        /// </summary>
        internal static string CourseIdInput_Page_Text_AccessCode_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Text_AccessCode_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theOptgroup.
        /// </summary>
        internal static string CourseIdInput_Page_UseAccessCode_RadioButton_Id_Locator {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_UseAccessCode_RadioButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register | Pearson MyLab &amp; Mastering.
        /// </summary>
        internal static string CourseIdInput_Page_Window_Title {
            get {
                return ResourceManager.GetString("CourseIdInput_Page_Window_Title", resourceCulture);
            }
        }
    }
}
