ALTER TABLE [dbo].[BDD_UserTypeLookUp]
    ADD CONSTRAINT [PK_BDD_UserTypeLookUp] PRIMARY KEY CLUSTERED ([UserTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

