ALTER TABLE [dbo].[BDD_OrgLeveTypeLookUp]
    ADD CONSTRAINT [PK_BDD_OrgLeveTypeLookUp] PRIMARY KEY CLUSTERED ([LevelID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

