ALTER TABLE [dbo].[BDD_Class]
    ADD CONSTRAINT [PK_BDD_Class] PRIMARY KEY CLUSTERED ([ClassId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

