//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Integration.Rumba {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignInPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignInPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Integration.Rumba.SignInPageResource", typeof(SignInPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string Key_Value_Separator {
            get {
                return ResourceManager.GetString("Key_Value_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string QueryString_Separator {
            get {
                return ResourceManager.GetString("QueryString_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string SignInPage_Custom_TimeToWait_Value {
            get {
                return ResourceManager.GetString("SignInPage_Custom_TimeToWait_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to RADmin.
        /// </summary>
        internal static string SignInPage_HomePage_Title_Name {
            get {
                return ResourceManager.GetString("SignInPage_HomePage_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containerLogin.
        /// </summary>
        internal static string SignInPage_LoginContainer_Id_Locator {
            get {
                return ResourceManager.GetString("SignInPage_LoginContainer_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearson Sign In.
        /// </summary>
        internal static string SignInPage_Logout_Window_Title {
            get {
                return ResourceManager.GetString("SignInPage_Logout_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string SignInPage_Password_Text_id_Locator {
            get {
                return ResourceManager.GetString("SignInPage_Password_Text_id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-submit.
        /// </summary>
        internal static string SignInPage_SignIn_Button_ClassName_Locator {
            get {
                return ResourceManager.GetString("SignInPage_SignIn_Button_ClassName_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        internal static string SignInPage_Signout_Link_Title_Locator {
            get {
                return ResourceManager.GetString("SignInPage_Signout_Link_Title_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;containerLogin&apos;]/h1.
        /// </summary>
        internal static string SignInPage_SignoutMessage_xpath_Locator {
            get {
                return ResourceManager.GetString("SignInPage_SignoutMessage_xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000.
        /// </summary>
        internal static string SignInPage_ThreadTimeToWait {
            get {
                return ResourceManager.GetString("SignInPage_ThreadTimeToWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string SignInPage_Username_Text_id_Locator {
            get {
                return ResourceManager.GetString("SignInPage_Username_Text_id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Url_Separator {
            get {
                return ResourceManager.GetString("Url_Separator", resourceCulture);
            }
        }
    }
}
