//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.SMSIntegration.ProgramManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewProductPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewProductPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.SMSIntegration.ProgramManagement.NewProduc" +
                            "tPageResource", typeof(NewProductPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL12345.
        /// </summary>
        internal static string NewProduct_Page_AccessCode_Characterset_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_AccessCode_Characterset_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtaccesscode.
        /// </summary>
        internal static string NewProduct_Page_AccessCode_Textbox_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_AccessCode_Textbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestDataFolder.
        /// </summary>
        internal static string NewProduct_Page_AppConfig_Key {
            get {
                return ResourceManager.GetString("NewProduct_Page_AppConfig_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \TestData\Product_Banner.png.
        /// </summary>
        internal static string NewProduct_Page_BannerImage_Name {
            get {
                return ResourceManager.GetString("NewProduct_Page_BannerImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal.
        /// </summary>
        internal static string NewProduct_Page_Basal_ProductType_DropDown_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_Basal_ProductType_DropDown_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoImg.
        /// </summary>
        internal static string NewProduct_Page_Button_BrowseBannerImage_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Button_BrowseBannerImage_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatalogImage.
        /// </summary>
        internal static string NewProduct_Page_Button_BrowseIconImage_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Button_BrowseIconImage_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcomeImage.
        /// </summary>
        internal static string NewProduct_Page_Button_BrowseWelcomeImage_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Button_BrowseWelcomeImage_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent.
        /// </summary>
        internal static string NewProduct_Page_Concurrent_LicensingType_DropDown_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_Concurrent_LicensingType_DropDown_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chkdemoproduct.
        /// </summary>
        internal static string NewProduct_Page_DemoProduct_Checkbox_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_DemoProduct_Checkbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drpDiscipline.
        /// </summary>
        internal static string NewProduct_Page_Discipline_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Discipline_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string NewProduct_Page_Discipline_DropDown_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_Discipline_DropDown_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtProgramName.
        /// </summary>
        internal static string NewProduct_Page_Hed_ProductName_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Hed_ProductName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40153.
        /// </summary>
        internal static string NewProduct_Page_Hed_SMSID_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_Hed_SMSID_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \TestData\Product_Icon.png.
        /// </summary>
        internal static string NewProduct_Page_IconImage_Name {
            get {
                return ResourceManager.GetString("NewProduct_Page_IconImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrmSearchProgram.
        /// </summary>
        internal static string NewProduct_Page_IFrameSearchProgram_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_IFrameSearchProgram_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrpLicenseModel.
        /// </summary>
        internal static string NewProduct_Page_LicensingType_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_LicensingType_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chkEnableITLab.
        /// </summary>
        internal static string NewProduct_Page_MyItLabProgramAdminReporting_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_MyItLabProgramAdminReporting_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NovaNet.
        /// </summary>
        internal static string NewProduct_Page_NovaNET_ProductType_DropDown_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_NovaNET_ProductType_DropDown_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdPegasusDataGrid$_ctrl1.
        /// </summary>
        internal static string NewProduct_Page_PegasusDataGrid_Ctrl1_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_PegasusDataGrid_Ctrl1_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdPegasusDataGrid.
        /// </summary>
        internal static string NewProduct_Page_PegasusDataGrid_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_PegasusDataGrid_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drpProductType.
        /// </summary>
        internal static string NewProduct_Page_ProductType_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_ProductType_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chkIsProgram.
        /// </summary>
        internal static string NewProduct_Page_ProgramType_CheckBox_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_ProgramType_CheckBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ancRightSearch.
        /// </summary>
        internal static string NewProduct_Page_RightSearch_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_RightSearch_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgbtnSave.
        /// </summary>
        internal static string NewProduct_Page_SaveButton_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_SaveButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtProductName.
        /// </summary>
        internal static string NewProduct_Page_School_ProductName_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_School_ProductName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSearch.
        /// </summary>
        internal static string NewProduct_Page_SearchButton_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_SearchButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdPegasusDataGrid&apos;]/tbody/tr/td[2]/a.
        /// </summary>
        internal static string NewProduct_Page_SearchProgram_Title_Xpath_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_SearchProgram_Title_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ancRightSearch.
        /// </summary>
        internal static string NewProduct_Page_SearchPrograms_Link_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_SearchPrograms_Link_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        internal static string NewProduct_Page_Seat_LicensingType_DropDown_Value {
            get {
                return ResourceManager.GetString("NewProduct_Page_Seat_LicensingType_DropDown_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtSMSID.
        /// </summary>
        internal static string NewProduct_Page_SMSID_TextBox_Id_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_SMSID_TextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSModuleID.
        /// </summary>
        internal static string NewProduct_Page_SMSModule_Id_Key {
            get {
                return ResourceManager.GetString("NewProduct_Page_SMSModule_Id_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucWelcomeEditor.
        /// </summary>
        internal static string NewProduct_Page_Welcome_Message_Editor_ID_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Welcome_Message_Editor_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebEditor.
        /// </summary>
        internal static string NewProduct_Page_Welcome_Message_WebEditor_ClassID_Locator {
            get {
                return ResourceManager.GetString("NewProduct_Page_Welcome_Message_WebEditor_ClassID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Product.
        /// </summary>
        internal static string NewProduct_Page_Window_Title_Name {
            get {
                return ResourceManager.GetString("NewProduct_Page_Window_Title_Name", resourceCulture);
            }
        }
    }
}
