//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.AssessmentTool.Presentation.AutoGrader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DownLoadStartingFilesPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownLoadStartingFilesPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.AssessmentTool.Presentation.AutoGrader.Dow" +
                            "nLoadStartingFilesPageResource", typeof(DownLoadStartingFilesPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCloseandReturn.
        /// </summary>
        internal static string DownLoadStartingFilePage_CloseAndReturn_Button_ID_Value {
            get {
                return ResourceManager.GetString("DownLoadStartingFilePage_CloseAndReturn_Button_ID_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and Return.
        /// </summary>
        internal static string DownLoadStartingFilePage_CloseAndReturn_Button_Text_Value {
            get {
                return ResourceManager.GetString("DownLoadStartingFilePage_CloseAndReturn_Button_Text_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblRepeater&apos;]/tbody/tr[{0}]/td[2]/input.
        /// </summary>
        internal static string DownLoadStartingFilesPage_DownloadIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("DownLoadStartingFilesPage_DownloadIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblRepeater&apos;]/tbody/tr[{0}].
        /// </summary>
        internal static string DownLoadStartingFilesPage_File_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("DownLoadStartingFilesPage_File_Name_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Starting Files.
        /// </summary>
        internal static string DownLoadStartingFilesPage_FileName_Popup_Title {
            get {
                return ResourceManager.GetString("DownLoadStartingFilesPage_FileName_Popup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblRepeater&apos;]/tbody/tr.
        /// </summary>
        internal static string DownLoadStartingFilesPage_FileName_RowCount_Xpath_Locator {
            get {
                return ResourceManager.GetString("DownLoadStartingFilesPage_FileName_RowCount_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DownLoadStartingFilesPage_Initial_Value {
            get {
                return ResourceManager.GetString("DownLoadStartingFilesPage_Initial_Value", resourceCulture);
            }
        }
    }
}
