//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.MMND.PortalTest.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserLayoutRootNodeTargetPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserLayoutRootNodeTargetPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.MMND.PortalTest.Portal.UserLayoutRootNodeTargetPageResourc" +
                            "e", typeof(UserLayoutRootNodeTargetPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignedToCopyInterval.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_AssignedToCopyInterval_AppSettings_Key_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_AssignedToCopyInterval_AppSettings_Key_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browserConfirmButton.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_BrowserConfirmation_Alert_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_BrowserConfirmation_Alert_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_BrowserConfirmation_ThreadTime {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_BrowserConfirmation_ThreadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PegasusMMND_PPE_Coord.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CoOrdinate_Course_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CoOrdinate_Course_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to your Courses page.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_BackToYourCoursesPage_Link_Text {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_BackToYourCoursesPage_Link_" +
                        "Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;top-table-holder&apos;]/table/tbody/tr[2]/td.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_CourseId_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_CourseId_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;bm&apos;]/div[{0}]/h4.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_CourseName_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_CourseName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Customized_Time {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Customized_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Customized_Wait_Time {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Customized_Wait_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Loop_Initializer {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Loop_Initializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Second_ArrayIndex_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Second_ArrayIndex_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;confirmationCourseSections&apos;]/li.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_SectionDetail_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_SectionDetail_Xpath_Locator" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Split_By_Bracket_Character {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Split_By_Bracket_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;pageheader&apos;]/h1.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Successful_Message_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Successful_Message_Xpath_Lo" +
                        "cator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;courses&apos;]/div[@class=&apos;box&apos;]/div/div[@class=&apos;bm&apos;]/div.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_TotalCourses_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_TotalCourses_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Create Confirmation.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Window_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseCreateConfirmation_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Home.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseHome_Text {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CourseHome_ThreadValue {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CourseHome_ThreadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseListLinkParent.
        /// </summary>
        internal static string UserLayoutRootNodetargetPage_CourseLoad_List_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodetargetPage_CourseLoad_List_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coordinator_course.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_CoOrdinatorCourse_DropDown_Name_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_CoOrdinatorCourse_DropDown_Name_" +
                        "Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_CoOrdinatorCourse_DropDown_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_CoOrdinatorCourse_DropDown_Value" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;coordinator_course&apos;]/option.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_AllOptions_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_AllOptions_Xpat" +
                        "h_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_Options_Initializer_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_Options_Initial" +
                        "izer_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;coordinator_course&apos;]/option[{0}].
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_Options_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Courses_DropDown_Options_Xpath_L" +
                        "ocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submitButton.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Go_Button_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Go_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchButton.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Search_RadioButton_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Search_RadioButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchid.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Search_Textbox_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Search_Textbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copyCoordinatorButton.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Section_RadioButton_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Section_RadioButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Copy a Course.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Window_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_CreateOrCopyACourse_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecollegeNotifierClose.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_eCollegeNotifier_Alert_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_eCollegeNotifier_Alert_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterAlert_Customized_Time {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterAlert_Customized_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to availableForCopy.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_AvailableForCopy_RadioButton_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_AvailableForCopy_RadioButton_" +
                        "Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CommaAndSpace_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CommaAndSpace_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseEnd.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseEnd_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseEnd_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course-name.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseName_Textbox_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseName_Textbox_Id_Locator" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseStart.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseStart_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseStart_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseTypeStudent.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseType_RadioButton_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CourseType_RadioButton_Id_Loc" +
                        "ator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;buttons&apos;]/button[2].
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_CreateCourseNow_Button_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_CreateCourseNow_Button_Xpath_" +
                        "Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Date_Parameter {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Date_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Month_Parameter {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Month_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_NextYear_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_NextYear_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Year_Parameter {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_DateTime_Year_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrollEnd.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_EnrollEnd_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_EnrollEnd_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrollStart.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_EnrollStart_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_EnrollStart_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course_name0.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_SectionName_Textbox_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_SectionName_Textbox_Id_Locato" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_SectionName_Value_Attribute {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_SectionName_Value_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_Space_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_Space_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Course Information.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_EnterCourseInformation_Window_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_EnterCourseInformation_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ENTER}.
        /// </summary>
        internal static string UserLayoutRootNodetargetPage_EnterKey {
            get {
                return ResourceManager.GetString("UserLayoutRootNodetargetPage_EnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;bi&apos;]/div[@class=&apos;bm&apos;]/div[{0}]/h4/img.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Course_Icon_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Course_Icon_Xpa" +
                        "th_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;bi&apos;]/div[@class=&apos;bm&apos;]/div[{0}]/h4.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Course_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Course_Name_Xpa" +
                        "th_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;bi&apos;]/div[@class=&apos;bm&apos;]/div[{0}]/div/h4/img.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Section_Icon_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Section_Icon_Xp" +
                        "ath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;bi&apos;]/div[@class=&apos;bm&apos;]/div[{0}]/div/h4.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Section_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_AssignedToCopy_Section_Name_Xp" +
                        "ath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pearsonLogOutLink.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_SignOut_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_SignOut_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_ThreadValue {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_ThreadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_Window_Sleep_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_Window_Sleep_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyLab &amp; Mastering | Pearson.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_MyLabMasteringPearson_Window_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_MyLabMasteringPearson_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PegasusMMND_PPE.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_NonCoOrdinate_Course_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_NonCoOrdinate_Course_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSearchTerm.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SearchTerm_AppSettings_Key_Value {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SearchTerm_AppSettings_Key_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;searchResults&apos;]/form/div[{0}]/table/tbody/tr/td[2]/h2.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_CourseName_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_CourseName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;searchResults&apos;]/form/div[{0}]/table/tbody/tr/td[3]/a.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_CourseType_Button_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_CourseType_Button_Xpath_Locato" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_Customized_Time {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_Customized_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchResults.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_Div_SearchResults_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_Div_SearchResults_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_Loop_Initializer {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_Loop_Initializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;searchResults&apos;]/form/div.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_TotalCourses_Xpath_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_TotalCourses_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course Materials.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_SelectCourseMaterials_Window_Title {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_SelectCourseMaterials_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_ShowContent_Alert_DisplayTime {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_ShowContent_Alert_DisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string UserLayoutRootNodeTargetPage_Signout_Link_PartialLinkText {
            get {
                return ResourceManager.GetString("UserLayoutRootNodeTargetPage_Signout_Link_PartialLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module.
        /// </summary>
        internal static string UserLayoutRootNodetargetPage_Subtab_Div_Id_Locator {
            get {
                return ResourceManager.GetString("UserLayoutRootNodetargetPage_Subtab_Div_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TAB}.
        /// </summary>
        internal static string UserLayoutRootNodetargetPage_TabKey {
            get {
                return ResourceManager.GetString("UserLayoutRootNodetargetPage_TabKey", resourceCulture);
            }
        }
    }
}
