//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutomationConfigurationManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationConfigurationManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Automation.AutomationConfigurationManagerResource", typeof(AutomationConfigurationManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserName_Key {
            get {
                return ResourceManager.GetString("BrowserName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootPPE.
        /// </summary>
        internal static string CourseSpaceURLRootPPE_Key {
            get {
                return ResourceManager.GetString("CourseSpaceURLRootPPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootPROD.
        /// </summary>
        internal static string CourseSpaceURLRootPROD_Key {
            get {
                return ResourceManager.GetString("CourseSpaceURLRootPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootST.
        /// </summary>
        internal static string CourseSpaceURLRootST_Key {
            get {
                return ResourceManager.GetString("CourseSpaceURLRootST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootVCD.
        /// </summary>
        internal static string CourseSpaceURLRootVCD_Key {
            get {
                return ResourceManager.GetString("CourseSpaceURLRootVCD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootVM.
        /// </summary>
        internal static string CourseSpaceURLRootVM_Key {
            get {
                return ResourceManager.GetString("CourseSpaceURLRootVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDCertAdminURLRoot.
        /// </summary>
        internal static string MMNDCertAdminURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDCertAdminURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDPPEAdminURLRoot.
        /// </summary>
        internal static string MMNDPPEAdminURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDPPEAdminURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDPPEPortalURLRoot.
        /// </summary>
        internal static string MMNDPPEPortalURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDPPEPortalURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDPRODAdminURLRoot.
        /// </summary>
        internal static string MMNDPRODAdminURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDPRODAdminURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDPRODPortalURLRoot.
        /// </summary>
        internal static string MMNDPRODPortalURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDPRODPortalURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMNDVMPortalURLRoot.
        /// </summary>
        internal static string MMNDVMPortalURLRoot_Key {
            get {
                return ResourceManager.GetString("MMNDVMPortalURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTInstructorResourceToolbarURLPPE.
        /// </summary>
        internal static string PCTInstructorResourceToolsPPE_Key {
            get {
                return ResourceManager.GetString("PCTInstructorResourceToolsPPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTInstructorResourceToolbarURLPROD.
        /// </summary>
        internal static string PCTInstructorResourceToolsPROD_Key {
            get {
                return ResourceManager.GetString("PCTInstructorResourceToolsPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTInstructorResourceToolbarURLST.
        /// </summary>
        internal static string PCTInstructorResourceToolsST_Key {
            get {
                return ResourceManager.GetString("PCTInstructorResourceToolsST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTInstructorResourceToolbarURLVM.
        /// </summary>
        internal static string PCTInstructorResourceToolsVM_Key {
            get {
                return ResourceManager.GetString("PCTInstructorResourceToolsVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootPPE.
        /// </summary>
        internal static string PEG_AUTOMATION_PPE_CSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_PPE_CSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootPPE.
        /// </summary>
        internal static string PEG_AUTOMATION_PPE_WSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_PPE_WSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootPROD.
        /// </summary>
        internal static string PEG_AUTOMATION_PROD_CSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_PROD_CSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootPROD.
        /// </summary>
        internal static string PEG_AUTOMATION_PROD_WSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_PROD_WSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootST.
        /// </summary>
        internal static string PEG_AUTOMATION_ST_CSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_ST_CSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootST.
        /// </summary>
        internal static string PEG_AUTOMATION_ST_WSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_ST_WSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootVCD.
        /// </summary>
        internal static string PEG_AUTOMATION_VCD_CSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_VCD_CSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootVCD.
        /// </summary>
        internal static string PEG_AUTOMATION_VCD_WSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_VCD_WSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSpaceURLRootVM.
        /// </summary>
        internal static string PEG_AUTOMATION_VM_CSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_VM_CSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootVM.
        /// </summary>
        internal static string PEG_AUTOMATION_VM_WSURL_Key {
            get {
                return ResourceManager.GetString("PEG_AUTOMATION_VM_WSURL_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEG_DOWNLOAD_PATH.
        /// </summary>
        internal static string PEG_DOWNLOAD_PATH_Key {
            get {
                return ResourceManager.GetString("PEG_DOWNLOAD_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEG_SMSAdminURLRoot.
        /// </summary>
        internal static string PEG_SMSAdminURLRoot_Key {
            get {
                return ResourceManager.GetString("PEG_SMSAdminURLRoot_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEG_TESTDATA_PATH.
        /// </summary>
        internal static string PEG_TESTDATA_PATH_Key {
            get {
                return ResourceManager.GetString("PEG_TESTDATA_PATH_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUMBAAdminURLRootPROD.
        /// </summary>
        internal static string RumbaURLRootPROD_Key {
            get {
                return ResourceManager.GetString("RumbaURLRootPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUMBAAdminURLRootST.
        /// </summary>
        internal static string RumbaURLRootST_Key {
            get {
                return ResourceManager.GetString("RumbaURLRootST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUMBAAdminURLRootVM.
        /// </summary>
        internal static string RumbaURLRootVM_Key {
            get {
                return ResourceManager.GetString("RumbaURLRootVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminStudentURLRootPPE.
        /// </summary>
        internal static string SMSAdminStudentURLRootPPE_Key {
            get {
                return ResourceManager.GetString("SMSAdminStudentURLRootPPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminStudentURLRootPROD.
        /// </summary>
        internal static string SMSAdminStudentURLRootPROD_Key {
            get {
                return ResourceManager.GetString("SMSAdminStudentURLRootPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminStudentURLRootVM.
        /// </summary>
        internal static string SMSAdminStudentURLRootVM_Key {
            get {
                return ResourceManager.GetString("SMSAdminStudentURLRootVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminURLRootPPE.
        /// </summary>
        internal static string SMSAdminURLRootPPE_Key {
            get {
                return ResourceManager.GetString("SMSAdminURLRootPPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminURLRootPROD.
        /// </summary>
        internal static string SMSAdminURLRootPROD_Key {
            get {
                return ResourceManager.GetString("SMSAdminURLRootPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminURLRootST.
        /// </summary>
        internal static string SMSAdminURLRootST_Key {
            get {
                return ResourceManager.GetString("SMSAdminURLRootST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSAdminURLRootVM.
        /// </summary>
        internal static string SMSAdminURLRootVM_Key {
            get {
                return ResourceManager.GetString("SMSAdminURLRootVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSInstructorAccessCodePPE.
        /// </summary>
        internal static string SMSInstructorAccessCodePPE_Key {
            get {
                return ResourceManager.GetString("SMSInstructorAccessCodePPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSInstructorAccessCodePROD.
        /// </summary>
        internal static string SMSInstructorAccessCodePROD_key {
            get {
                return ResourceManager.GetString("SMSInstructorAccessCodePROD_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSInstructorAccessCodeST.
        /// </summary>
        internal static string SMSInstructorAccessCodeST_Key {
            get {
                return ResourceManager.GetString("SMSInstructorAccessCodeST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSInstructorAccessCodeVM.
        /// </summary>
        internal static string SMSInstructorAccessCodeVM_Key {
            get {
                return ResourceManager.GetString("SMSInstructorAccessCodeVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSModuleIDPPE.
        /// </summary>
        internal static string SMSModuleIDPPE_key {
            get {
                return ResourceManager.GetString("SMSModuleIDPPE_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSModuleIDPROD.
        /// </summary>
        internal static string SMSModuleIDPROD_key {
            get {
                return ResourceManager.GetString("SMSModuleIDPROD_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSModuleIDST.
        /// </summary>
        internal static string SMSModuleIDST_Key {
            get {
                return ResourceManager.GetString("SMSModuleIDST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSModuleIDVM.
        /// </summary>
        internal static string SMSModuleIDVM_key {
            get {
                return ResourceManager.GetString("SMSModuleIDVM_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSStudentAccessCodePPE.
        /// </summary>
        internal static string SMSStudentAccessCodePPE_Key {
            get {
                return ResourceManager.GetString("SMSStudentAccessCodePPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSStudentAccessCodePROD.
        /// </summary>
        internal static string SMSStudentAccessCodePROD_Key {
            get {
                return ResourceManager.GetString("SMSStudentAccessCodePROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSStudentAccessCodeST.
        /// </summary>
        internal static string SMSStudentAccessCodeST_Key {
            get {
                return ResourceManager.GetString("SMSStudentAccessCodeST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSStudentAccessCodeVM.
        /// </summary>
        internal static string SMSStudentAccessCodeVM_Key {
            get {
                return ResourceManager.GetString("SMSStudentAccessCodeVM_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestEnvironment.
        /// </summary>
        internal static string TestEnvironment_Key {
            get {
                return ResourceManager.GetString("TestEnvironment_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootPPE.
        /// </summary>
        internal static string WorkSpaceURLRootPPE_Key {
            get {
                return ResourceManager.GetString("WorkSpaceURLRootPPE_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootPROD.
        /// </summary>
        internal static string WorkSpaceURLRootPROD_Key {
            get {
                return ResourceManager.GetString("WorkSpaceURLRootPROD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootST.
        /// </summary>
        internal static string WorkSpaceURLRootST_Key {
            get {
                return ResourceManager.GetString("WorkSpaceURLRootST_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootVCD.
        /// </summary>
        internal static string WorkSpaceURLRootVCD_Key {
            get {
                return ResourceManager.GetString("WorkSpaceURLRootVCD_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSpaceURLRootVM.
        /// </summary>
        internal static string WorkSpaceURLRootVM_Key {
            get {
                return ResourceManager.GetString("WorkSpaceURLRootVM_Key", resourceCulture);
            }
        }
    }
}
