ALTER TABLE [dbo].[BDD_Product]
    ADD CONSTRAINT [PK__BDD_Prod__B40CC6ED1FCDBCEB] PRIMARY KEY CLUSTERED ([ProductID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

