ALTER TABLE [dbo].[BDD_Organization]
    ADD CONSTRAINT [PK_BDD_Organization] PRIMARY KEY CLUSTERED ([OrgID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

