ALTER TABLE [dbo].[BDD_TemplateTypeLookUp]
    ADD CONSTRAINT [PK_BDD_TemplateTypeLookUp] PRIMARY KEY CLUSTERED ([TemplateTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

