ALTER TABLE [dbo].[BDD_QuestionTypeLookUp]
    ADD CONSTRAINT [PK_BDD_QuestionTypeLookUp] PRIMARY KEY CLUSTERED ([QuestionTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

