ALTER TABLE [dbo].[BDD_Activity]
    ADD CONSTRAINT [PK_BDD_Activity] PRIMARY KEY CLUSTERED ([ActivityID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

