ALTER TABLE [dbo].[BDD_ProgramTypeLookUp]
    ADD CONSTRAINT [PK_BDD_ProgramTypeLookUp] PRIMARY KEY CLUSTERED ([ProgramTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

