ALTER TABLE [dbo].[BDD_OrgTypeLookUp]
    ADD CONSTRAINT [PK_BDD_OrgTypeLookUp] PRIMARY KEY CLUSTERED ([OrgTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

