ALTER TABLE [dbo].[BDD_Template]
    ADD CONSTRAINT [PK_BDD_Template] PRIMARY KEY CLUSTERED ([TemplateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

