ALTER TABLE [dbo].[BDD_ProductTypeLookUp]
    ADD CONSTRAINT [PK_BDD_ProductTypeLookUp] PRIMARY KEY CLUSTERED ([ProductTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

