//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.HomePage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalendarFramePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarFramePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.HomePage.CalendarFramePageResource", typeof(CalendarFramePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[@title=&apos;Assigned&apos;].
        /// </summary>
        internal static string CalendarFrame_Page_CalendarIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_CalendarIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Materials.
        /// </summary>
        internal static string CalendarFrame_Page_CourseMaterials_Window_Name {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_CourseMaterials_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iframe1.
        /// </summary>
        internal static string CalendarFrame_Page_Frame_Id_Locator {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_Frame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string CalendarFrame_Page_Overview_Window_Name {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_Overview_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calIframe.
        /// </summary>
        internal static string CalendarFrame_Page_Preview_CalendarFrame_Id_Locator {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_Preview_CalendarFrame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrmCoursePreview.
        /// </summary>
        internal static string CalendarFrame_Page_Preview_Frame_Id_Locator {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_Preview_Frame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s View.
        /// </summary>
        internal static string CalendarFrame_Page_TodaysView_Window_Title {
            get {
                return ResourceManager.GetString("CalendarFrame_Page_TodaysView_Window_Title", resourceCulture);
            }
        }
    }
}
