//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.LtiIntegeration.RLCNUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RLCNUtilityPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RLCNUtilityPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.LtiIntegeration.RLCNUtility.RLCNUtilityPag" +
                            "eResource", typeof(RLCNUtilityPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;ui-datepicker-calendar&apos;]/tbody/tr[{0}]/td.
        /// </summary>
        internal static string RLCNUtility_Page_Calendar_ColumnCount_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Calendar_ColumnCount_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;ui-datepicker-calendar&apos;]/tbody/tr[{0}]/td[{1}]/a.
        /// </summary>
        internal static string RLCNUtility_Page_Calendar_DateValueInColumn_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Calendar_DateValueInColumn_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;ui-datepicker-calendar&apos;]/tbody/tr.
        /// </summary>
        internal static string RLCNUtility_Page_Calendar_RowCount_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Calendar_RowCount_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div.
        /// </summary>
        internal static string RLCNUtility_Page_Calendar_Widget_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Calendar_Widget_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;repeaterdiv&apos;]/div.
        /// </summary>
        internal static string RLCNUtility_Page_CourseTitle_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_CourseTitle_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;rptFailedRLCNrequests__ctl0_coursetitle&apos;].
        /// </summary>
        internal static string RLCNUtility_Page_CourseTitle_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_CourseTitle_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui-state-default ui-state-highlight ui-state-hover.
        /// </summary>
        internal static string RLCNUtility_Page_CurrentDate_ClassName_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_CurrentDate_ClassName_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table tbody tr td select#databaseNames option.
        /// </summary>
        internal static string RLCNUtility_Page_DataBase_Name_DropDown_CSSSelector_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_DataBase_Name_DropDown_CSSSelector_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseNames.
        /// </summary>
        internal static string RLCNUtility_Page_DataBase_Name_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_DataBase_Name_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtEndDateTime.
        /// </summary>
        internal static string RLCNUtility_Page_EndDate_Text_ID_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_EndDate_Text_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/form/div/div[2]/div[1]/table/tbody/tr/td[8]/div/table/tbody/tr[1]/td/img.
        /// </summary>
        internal static string RLCNUtility_Page_EndDatePicker_Image_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_EndDatePicker_Image_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;fetch&apos;].
        /// </summary>
        internal static string RLCNUtility_Page_Fetch_Button_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Fetch_Button_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;rptFailedRLCNrequests__ctl0_lnkresolve&apos;].
        /// </summary>
        internal static string RLCNUtility_Page_Resolve_Link_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_Resolve_Link_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLCN Failed Requests.
        /// </summary>
        internal static string RLCNUtility_Page_RLCNFailedRequests_Window_Title_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_RLCNFailedRequests_Window_Title_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string RLCNUtility_Page_SleepTime_Value {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_SleepTime_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtstartDateTime.
        /// </summary>
        internal static string RLCNUtility_Page_StartDate_Text_ID_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_StartDate_Text_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/form/div/div[2]/div[1]/table/tbody/tr/td[5]/div/table/tbody/tr[1]/td/img.
        /// </summary>
        internal static string RLCNUtility_Page_StartDatePicker_Image_Xpath_Locator {
            get {
                return ResourceManager.GetString("RLCNUtility_Page_StartDatePicker_Image_Xpath_Locator", resourceCulture);
            }
        }
    }
}
