//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.Planner.Calendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreatePeriodsPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatePeriodsPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.Planner.Calendar.CreatePeriodsPageResource" +
                            "", typeof(CreatePeriodsPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn_Finish.
        /// </summary>
        internal static string CreatePeriodsPage_Button_Save_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Button_Save_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkFri.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Friday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Friday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkMon.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Monday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Monday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkSat.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Saturday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Saturday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkSun.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Sunday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Sunday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkThu.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Thursday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Thursday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkTue.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Tuesday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Tuesday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChkWed.
        /// </summary>
        internal static string CreatePeriodsPage_Checkbox_Wednesday_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Checkbox_Wednesday_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrpClassAsso.
        /// </summary>
        internal static string CreatePeriodsPage_ClassAssociations_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_ClassAssociations_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CreatePeriodsPage_ClassAssociations_DropDown_Index_Value {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_ClassAssociations_DropDown_Index_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrpCourseAsso.
        /// </summary>
        internal static string CreatePeriodsPage_CourseAssociations_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_CourseAssociations_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CreatePeriodsPage_CourseAssociations_DropDown_Index_Value {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_CourseAssociations_DropDown_Index_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmCreatePeriod.
        /// </summary>
        internal static string CreatePeriodsPage_Iframe_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Iframe_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrpPeriodOrder.
        /// </summary>
        internal static string CreatePeriodsPage_Order_DropDown_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Order_DropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CreatePeriodsPage_Order_DropDown_Index_Value {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Order_DropDown_Index_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPeriodName.
        /// </summary>
        internal static string CreatePeriodsPage_Textbox_PeriodName_Id_Locator {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Textbox_PeriodName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar_Automation.
        /// </summary>
        internal static string CreatePeriodsPage_Textbox_PeriodName_Value {
            get {
                return ResourceManager.GetString("CreatePeriodsPage_Textbox_PeriodName_Value", resourceCulture);
            }
        }
    }
}
