//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.QuestionLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EssayPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EssayPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.QuestionLibrary.EssayPageResource", typeof(EssayPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spnAnswer.
        /// </summary>
        internal static string Essay_Page_Answer_Button_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_Answer_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_chkAudio.
        /// </summary>
        internal static string Essay_Page_AudioInput_Checkbox_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_AudioInput_Checkbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtMin.
        /// </summary>
        internal static string Essay_Page_AudioInput_MinTime_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_AudioInput_MinTime_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Essay_Page_AudioInput_Minutes_Time_Value {
            get {
                return ResourceManager.GetString("Essay_Page_AudioInput_Minutes_Time_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtSec.
        /// </summary>
        internal static string Essay_Page_AudioInput_Seconds_Time_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_AudioInput_Seconds_Time_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Essay_Page_AudioInput_Seconds_Time_Value {
            get {
                return ResourceManager.GetString("Essay_Page_AudioInput_Seconds_Time_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recordaudio.
        /// </summary>
        internal static string Essay_Page_AudioRecord_Image_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_AudioRecord_Image_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1:btnImgbrow.
        /// </summary>
        internal static string Essay_Page_Browse_Button_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_Browse_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdCharPalette4.
        /// </summary>
        internal static string Essay_Page_CharacterPallete_Id_Locator_five {
            get {
                return ResourceManager.GetString("Essay_Page_CharacterPallete_Id_Locator_five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdCharPalette3.
        /// </summary>
        internal static string Essay_Page_CharacterPallete_Id_Locator_four {
            get {
                return ResourceManager.GetString("Essay_Page_CharacterPallete_Id_Locator_four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdCharPalette0.
        /// </summary>
        internal static string Essay_Page_CharacterPallete_Id_Locator_one {
            get {
                return ResourceManager.GetString("Essay_Page_CharacterPallete_Id_Locator_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdCharPalette2.
        /// </summary>
        internal static string Essay_Page_CharacterPallete_Id_Locator_three {
            get {
                return ResourceManager.GetString("Essay_Page_CharacterPallete_Id_Locator_three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdCharPalette1.
        /// </summary>
        internal static string Essay_Page_CharacterPallete_Id_Locator_two {
            get {
                return ResourceManager.GetString("Essay_Page_CharacterPallete_Id_Locator_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Essay.
        /// </summary>
        internal static string Essay_Page_CreateEssay_Window_Name {
            get {
                return ResourceManager.GetString("Essay_Page_CreateEssay_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtQuestionLabel.
        /// </summary>
        internal static string Essay_Page_EnterQuestionTitle_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_EnterQuestionTitle_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucEditorA_textarea.
        /// </summary>
        internal static string Essay_Page_EnterText_HTML_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_EnterText_HTML_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_ifrmEditor_A.
        /// </summary>
        internal static string Essay_Page_HTMLFrame_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_HTMLFrame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtMaxScore.
        /// </summary>
        internal static string Essay_Page_MaxScore_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_MaxScore_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        internal static string Essay_Page_MaxScore_Value {
            get {
                return ResourceManager.GetString("Essay_Page_MaxScore_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrative Image.
        /// </summary>
        internal static string Essay_Page_NarrativeImage_Name {
            get {
                return ResourceManager.GetString("Essay_Page_NarrativeImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtNumberOfLines.
        /// </summary>
        internal static string Essay_Page_NumberOfLines_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_NumberOfLines_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Essay_Page_NumberOfLines_Value {
            get {
                return ResourceManager.GetString("Essay_Page_NumberOfLines_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl1_txtNumberOfWords.
        /// </summary>
        internal static string Essay_Page_NumberOfWords_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_NumberOfWords_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Essay_Page_NumberOfWords_Value {
            get {
                return ResourceManager.GetString("Essay_Page_NumberOfWords_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Audio.
        /// </summary>
        internal static string Essay_Page_RecordAudio_Window_Name {
            get {
                return ResourceManager.GetString("Essay_Page_RecordAudio_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lrn_btn lrn_start_recording.
        /// </summary>
        internal static string Essay_Page_RecordButton_ClassName {
            get {
                return ResourceManager.GetString("Essay_Page_RecordButton_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgReturnf.
        /// </summary>
        internal static string Essay_Page_Save_Button_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_Save_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmSelectQuestion.
        /// </summary>
        internal static string Essay_Page_Select_CreateQuestion_Frame {
            get {
                return ResourceManager.GetString("Essay_Page_Select_CreateQuestion_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Question.
        /// </summary>
        internal static string Essay_Page_Select_CreateQuestion_Window_Name {
            get {
                return ResourceManager.GetString("Essay_Page_Select_CreateQuestion_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewsource.
        /// </summary>
        internal static string Essay_Page_ViewSource_Button_Id_Locator {
            get {
                return ResourceManager.GetString("Essay_Page_ViewSource_Button_Id_Locator", resourceCulture);
            }
        }
    }
}
