//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.TeachingPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentBrowserUXPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentBrowserUXPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.TeachingPlan.ContentBrowserUXPageResource", typeof(ContentBrowserUXPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdContentBrowser&apos;]/tbody/tr.
        /// </summary>
        internal static string ContentBrowserUX_Page_ActivityCount_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_ActivityCount_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_imgBtnAdd_Close.
        /// </summary>
        internal static string ContentBrowserUX_Page_AddAndClose_Button_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AddAndClose_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_imgBtnAdd_Close.
        /// </summary>
        internal static string ContentBrowserUX_Page_AddandClose_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AddandClose_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Close.
        /// </summary>
        internal static string ContentBrowserUX_Page_AddandClose_Link_PartialLinktext_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AddandClose_Link_PartialLinktext_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chkAllQuestionTypes.
        /// </summary>
        internal static string ContentBrowserUX_Page_AdvancedSearch_AllQuestionTypes_CheckBox_Id {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AdvancedSearch_AllQuestionTypes_CheckBox_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iWindow.
        /// </summary>
        internal static string ContentBrowserUX_Page_AdvancedSearch_AllQuestionTypes_CheckBox_IframeId_locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AdvancedSearch_AllQuestionTypes_CheckBox_IframeId_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string ContentBrowserUX_Page_AdvancedSearch_Link_PartialText {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AdvancedSearch_Link_PartialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnAdvSearch.
        /// </summary>
        internal static string ContentBrowserUX_Page_AdvancedSearch_Search_Button_Id {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AdvancedSearch_Search_Button_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chkQuestionTypeList_4.
        /// </summary>
        internal static string ContentBrowserUX_Page_AdvancedSearch_SIM5Question_CheckBox_Id {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AdvancedSearch_SIM5Question_CheckBox_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string ContentBrowserUX_Page_AfterClickSave_Button_Sleep_Time {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_AfterClickSave_Button_Sleep_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdContentBrowser$divContent.
        /// </summary>
        internal static string ContentBrowserUX_Page_Content_Div_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Content_Div_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_imgBtnAdd_Close.
        /// </summary>
        internal static string ContentBrowserUX_Page_CourseMaterialsLibrary_AddAndClose_Button_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_CourseMaterialsLibrary_AddAndClose_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdContentBrowser$_ctrl1.
        /// </summary>
        internal static string ContentBrowserUX_Page_CourseMaterialsLibrary_FirstSIM5Question_CheckBox_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_CourseMaterialsLibrary_FirstSIM5Question_CheckBox_Id_Locato" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_ifrmLeft.
        /// </summary>
        internal static string ContentBrowserUX_Page_CourseMaterialsLibrary_Iframe_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_CourseMaterialsLibrary_Iframe_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_PopupPageContent_ifrmLeft.
        /// </summary>
        internal static string ContentBrowserUX_Page_Frame_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Frame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_InnerPageContent_ucSearchPanel_btnSearchGo.
        /// </summary>
        internal static string ContentBrowserUX_Page_Go_Button_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Go_Button_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Questions Folder.
        /// </summary>
        internal static string ContentBrowserUX_Page_Hed_QuestionFolder_Level1_Name {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Hed_QuestionFolder_Level1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ContentBrowserUX_Page_Load_SecondTime {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Load_SecondTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdContentBrowser$_ctrl1.
        /// </summary>
        internal static string ContentBrowserUX_Page_Question_Checkbox_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Question_Checkbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdContentBrowser.
        /// </summary>
        internal static string ContentBrowserUX_Page_QuestionContainer_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_QuestionContainer_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdContentBrowser&apos;]/tbody/tr.
        /// </summary>
        internal static string ContentBrowserUX_Page_QuestionContainer_Row_XPath_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_QuestionContainer_Row_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdContentBrowser&apos;]/tbody/tr[{0}]/td[2]/table/tbody/tr/td[2]/a.
        /// </summary>
        internal static string ContentBrowserUX_Page_QuestionName_Link_XPath_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_QuestionName_Link_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copy to.
        /// </summary>
        internal static string ContentBrowserUX_Page_Savecopyto_Window_Title_Name {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Savecopyto_Window_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_InnerPageContent_ucSearchPanel_txtSearch.
        /// </summary>
        internal static string ContentBrowserUX_Page_Search_Textbox_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Search_Textbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select content.
        /// </summary>
        internal static string ContentBrowserUx_Page_SelectContent_Window_Name {
            get {
                return ResourceManager.GetString("ContentBrowserUx_Page_SelectContent_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdContentBrowser$_ctrl0.
        /// </summary>
        internal static string ContentBrowserUX_Page_SelectQuestion_Checkbox_Id_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_SelectQuestion_Checkbox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Questions.
        /// </summary>
        internal static string ContentBrowserUX_Page_SelectQuestions_Window_Name {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_SelectQuestions_Window_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string ContentBrowserUX_Page_Sleep_Time {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Sleep_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdContentBrowser&apos;]/tbody/tr[{0}]/td[2].
        /// </summary>
        internal static string ContentBrowserUX_Page_Student_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Student_Name_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdContentBrowser&apos;]/tbody/tr[{0}]/td[1]/input.
        /// </summary>
        internal static string ContentBrowserUX_Page_Student_RadioButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Student_RadioButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Existing Activity.
        /// </summary>
        internal static string ContentBrowserUX_Page_Window_Title_Name {
            get {
                return ResourceManager.GetString("ContentBrowserUX_Page_Window_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0_InnerPageContent_ucSearchPanel_lnkAdvSearch.
        /// </summary>
        internal static string ContentBrtowserUX_Page_AdvancedSearch_Div_Id_locator {
            get {
                return ResourceManager.GetString("ContentBrtowserUX_Page_AdvancedSearch_Div_Id_locator", resourceCulture);
            }
        }
    }
}
