//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.UI_Pages.Pegasus.Modules.TeachingPlan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoursePreviewUXPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoursePreviewUXPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.UI_Pages.Pegasus.Modules.TeachingPlan.CoursePreviewUXPageResource", typeof(CoursePreviewUXPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments - To Do.
        /// </summary>
        internal static string CouresPreviewUX_Page_AssignmentsToDo_Window_Title {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_AssignmentsToDo_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div[{0}].
        /// </summary>
        internal static string CouresPreviewUX_Page_DivTodoListNodes_XPath_Locator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_DivTodoListNodes_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        internal static string CouresPreviewUX_Page_ToDo_Window_Title {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_ToDo_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoList_XPath_Locator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoList_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div[{0}]/descendant::td[@class=&apos;coloumn_4&apos;]/div/a.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoListNodes_XPath_Locator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoListNodes_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div/div.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_AssetCount_XPath_Locator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_AssetCount_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div/div[{0}]/div/div[2]/table/tbody/tr/td[2]/div[1].
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_AssetName_XPathLocator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_AssetName_XPathLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div/div[{0}]/div/div[2]/table/tbody/tr/td[3]/div[1]/div/div[2].
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_AssetStatus_XPathLocator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_AssetStatus_XPathLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_Completed_PartialLinkText {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_Completed_PartialLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAll Course Material.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_Iframe_Name {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_Iframe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;TodoList&apos;]/div/div[{0}]/div/div[2]/table/tbody/tr/td[4]/div/a/span.
        /// </summary>
        internal static string CouresPreviewUX_Page_TodoPage_ImDone_XPath_Locator {
            get {
                return ResourceManager.GetString("CouresPreviewUX_Page_TodoPage_ImDone_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblCoursePreview&apos;]/tbody/tr.
        /// </summary>
        internal static string CoursePreviewUX_Page_Activity_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Activity_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CoursePreviewUX_Page_Activity_Counter {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Activity_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to essay.
        /// </summary>
        internal static string CoursePreviewUX_Page_Activity_Essay_Text_to_Fill {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Activity_Essay_Text_to_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string CoursePreviewUX_Page_Activity_WebElement_Property_Name {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Activity_WebElement_Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM Activity.
        /// </summary>
        internal static string CoursePreviewUX_Page_Activity_Window_Title_Name_HED {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Activity_Window_Title_Name_HED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblCoursePreview&apos;]/tbody/tr[{0}].
        /// </summary>
        internal static string CoursePreviewUX_Page_ActivityName_Xpath_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_ActivityName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblCoursePreview&apos;]/tbody/tr.
        /// </summary>
        internal static string CoursePreviewUX_Page_Assets_Count_Xpath_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Assets_Count_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblCoursePreview&apos;]/tbody/tr[{0}]/td[2]/table/tbody/tr/td/table/tbody/tr/td/a.
        /// </summary>
        internal static string CoursePreviewUX_Page_Assets_Name_Xpath_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Assets_Name_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .coloumn_2.
        /// </summary>
        internal static string CoursePreviewUX_Page_Coloumn2_CssSelector_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Coloumn2_CssSelector_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tblCoursePreview.
        /// </summary>
        internal static string CoursePreviewUX_Page_CoursePreview_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_CoursePreview_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrmCoursePreview.
        /// </summary>
        internal static string CoursePreviewUX_Page_CoursePreview_IFrame_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_CoursePreview_IFrame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string CoursePreviewUX_Page_Customized_TimeOut {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Customized_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl0__ctl0_phHeader__ctl0_ucs_Toolbar_ucs_SubMenubar_ucs_RT_tdHEDEbook.
        /// </summary>
        internal static string CoursePreviewUX_Page_Etext_Link {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Etext_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrmCoursePreview.
        /// </summary>
        internal static string CoursePreviewUX_Page_IFrame_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_IFrame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .btn_Done_m.
        /// </summary>
        internal static string CoursePreviewUX_Page_ImDone_Button_Class_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_ImDone_Button_Class_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CoursePreviewUX_Page_Loop_Initialization_Value {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Loop_Initialization_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC_Past_due.
        /// </summary>
        internal static string CoursePreviewUX_Page_PastDueDateIcon_Class_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_PastDueDateIcon_Class_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span_.
        /// </summary>
        internal static string CoursePreviewUX_Page_PastDueDateIcon_WebelementProperty_Id_PartialValue {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_PastDueDateIcon_WebelementProperty_Id_PartialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;{0}&apos;]/img.
        /// </summary>
        internal static string CoursePreviewUX_Page_PastDueDateIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_PastDueDateIcon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txtMinorcss.
        /// </summary>
        internal static string CoursePreviewUX_Page_ScoreValue_CssSelector_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_ScoreValue_CssSelector_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7000.
        /// </summary>
        internal static string CoursePreviewUX_Page_Search_Time_Value {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Search_Time_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string CoursePreviewUX_Page_Sleep_Time {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Sleep_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[id=&apos;btnStart&apos;].
        /// </summary>
        internal static string CoursePreviewUX_Page_StartButton_CssSelector_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_StartButton_CssSelector_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodoList.
        /// </summary>
        internal static string CoursePreviewUX_Page_ToDoList_Div_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_ToDoList_Div_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .btn_TryAgain.
        /// </summary>
        internal static string CoursePreviewUX_Page_TryAgain_Button_Class_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_TryAgain_Button_Class_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Materials.
        /// </summary>
        internal static string CoursePreviewUX_Page_Window_Title_Name_HED {
            get {
                return ResourceManager.GetString("CoursePreviewUX_Page_Window_Title_Name_HED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string CoursePreviewUXPage_ElementLoad_Time_Value {
            get {
                return ResourceManager.GetString("CoursePreviewUXPage_ElementLoad_Time_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rptCoursePreview$next.
        /// </summary>
        internal static string CoursePreviewUXPage_Searched_Table_Next_Id_Locator {
            get {
                return ResourceManager.GetString("CoursePreviewUXPage_Searched_Table_Next_Id_Locator", resourceCulture);
            }
        }
    }
}
