CREATE TABLE [dbo].[BDD_CourseTypeLookUp] (
    [CourseTypeID] INT            NOT NULL,
    [CourseType]   NVARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([CourseTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

