CREATE TABLE [dbo].[BDD_UrlInfo] (
    [WS_URL]    VARCHAR (1000) NULL,
    [CS_URL]    VARCHAR (1000) NULL,
    [WSURL_HED] VARCHAR (1000) NULL,
    [CSURL_HED] VARCHAR (1000) NULL,
    [SMS_URL]   VARCHAR (1000) NULL,
    [RUMBA_URL] VARCHAR (1000) NULL
);

